displayName: AC360
schemaName: cra7f_AC360
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cra7f_AC360.gpt.default

  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    contentModeration: Low
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

template: default-2.1.0
language: 1036